using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using OldSchoolLab.Models;

namespace OldSchoolLab.Data;

public static class SeedData
{
    public static async Task InitializeAsync(IServiceProvider services)
    {
        using var scope = services.CreateScope();
        var scopedServices = scope.ServiceProvider;

        var db = scopedServices.GetRequiredService<ApplicationDbContext>();
        var userManager = scopedServices.GetRequiredService<UserManager<ApplicationUser>>();
        var roleManager = scopedServices.GetRequiredService<RoleManager<IdentityRole>>();

        await db.Database.EnsureCreatedAsync();

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Companies" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(120) NOT NULL,
                "LogoPath" character varying(200) NOT NULL DEFAULT '',
                "LogoFileName" character varying(120) NOT NULL DEFAULT '',
                "IsActive" boolean NOT NULL DEFAULT TRUE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Companies_Name"
            ON "Companies" ("Name");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "AspNetUsers"
            ADD COLUMN IF NOT EXISTS "CompanyId" integer NULL;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "Products"
            ADD COLUMN IF NOT EXISTS "CompanyId" integer NULL;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "Statuses"
            ADD COLUMN IF NOT EXISTS "CompanyId" integer NULL;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecords"
            ADD COLUMN IF NOT EXISTS "CompanyId" integer NULL;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "AuditLogs"
            ADD COLUMN IF NOT EXISTS "CompanyId" integer NULL;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecords"
            ALTER COLUMN "RecordDate" TYPE date
            USING "RecordDate"::date;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "AuditLogs"
            ALTER COLUMN "ChangedAt" TYPE timestamp without time zone
            USING "ChangedAt"::timestamp without time zone;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "CustomerRecordPayments" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CustomerRecordId" integer NOT NULL,
                "Amount" numeric(10,2) NOT NULL,
                "PaymentDate" date NOT NULL,
                "CreatedAt" timestamp without time zone NOT NULL,
                "ProofImagePath" character varying(260) NOT NULL DEFAULT '',
                "ProofFileName" character varying(120) NOT NULL DEFAULT '',
                "CreatedByUserId" character varying(450) NOT NULL DEFAULT '',
                "CreatedByUserName" character varying(120) NOT NULL DEFAULT '',
                CONSTRAINT "FK_CustomerRecordPayments_CustomerRecords_CustomerRecordId"
                    FOREIGN KEY ("CustomerRecordId") REFERENCES "CustomerRecords" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_CustomerRecordPayments_CustomerRecordId_PaymentDate"
            ON "CustomerRecordPayments" ("CustomerRecordId", "PaymentDate");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecordPayments"
            ALTER COLUMN "PaymentDate" TYPE date
            USING "PaymentDate"::date;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecordPayments"
            ALTER COLUMN "CreatedAt" TYPE timestamp without time zone
            USING "CreatedAt"::timestamp without time zone;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecordPayments"
            ADD COLUMN IF NOT EXISTS "IsReversed" boolean NOT NULL DEFAULT FALSE;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecordPayments"
            ADD COLUMN IF NOT EXISTS "ReversedAt" timestamp without time zone NULL;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecordPayments"
            ADD COLUMN IF NOT EXISTS "ReversedByUserId" character varying(450) NOT NULL DEFAULT '';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecordPayments"
            ADD COLUMN IF NOT EXISTS "ReversedByUserName" character varying(120) NOT NULL DEFAULT '';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecordPayments"
            ADD COLUMN IF NOT EXISTS "OperationNumber" character varying(50) NOT NULL DEFAULT '';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE IF EXISTS "CustomerRecordPayments"
            ALTER COLUMN "ReversedAt" TYPE timestamp without time zone
            USING "ReversedAt"::timestamp without time zone;
            """);

        var company = await db.Companies.FirstOrDefaultAsync(x => x.Name == "Old School Lab");
        if (company is null)
        {
            company = new Company { Name = "Old School Lab", IsActive = true };
            db.Companies.Add(company);
            await db.SaveChangesAsync();
        }

        await db.Database.ExecuteSqlRawAsync($"UPDATE \"Products\" SET \"CompanyId\" = {company.Id} WHERE \"CompanyId\" IS NULL;");
        await db.Database.ExecuteSqlRawAsync($"UPDATE \"Statuses\" SET \"CompanyId\" = {company.Id} WHERE \"CompanyId\" IS NULL;");
        await db.Database.ExecuteSqlRawAsync($"UPDATE \"CustomerRecords\" SET \"CompanyId\" = {company.Id} WHERE \"CompanyId\" IS NULL;");
        await db.Database.ExecuteSqlRawAsync($"UPDATE \"AuditLogs\" SET \"CompanyId\" = {company.Id} WHERE \"CompanyId\" IS NULL;");

        await db.Database.ExecuteSqlRawAsync("""
            DROP INDEX IF EXISTS "IX_Statuses_Name";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Statuses_CompanyId_Name"
            ON "Statuses" ("CompanyId", "Name");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            DROP INDEX IF EXISTS "IX_Products_Name";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_CompanyId_Name"
            ON "Products" ("CompanyId", "Name");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            INSERT INTO "CustomerRecordPayments"
                ("CustomerRecordId", "Amount", "PaymentDate", "CreatedAt", "ProofImagePath", "ProofFileName", "CreatedByUserId", "CreatedByUserName")
            SELECT
                r."Id",
                r."PaidAmount",
                r."RecordDate",
                NOW()::timestamp without time zone,
                '',
                '',
                r."CreatedByUserId",
                r."CreatedByUserName"
            FROM "CustomerRecords" r
            WHERE r."PaidAmount" > 0
              AND NOT EXISTS (
                  SELECT 1
                  FROM "CustomerRecordPayments" p
                  WHERE p."CustomerRecordId" = r."Id"
              );
            """);

        var roles = new[] { "SuperAdmin", "AdminEmpresa", "Gerencia", "Gestor", "Monitoreo", "Vendedor" };
        foreach (var role in roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole(role));
            }
        }

        await EnsureUserAsync(userManager, "ADMIN", "ADMIN", "Gerencia", company.Id);
        await EnsureUserAsync(userManager, "gerencia", "Gerencia123!", "Gerencia", company.Id);
        await EnsureUserAsync(userManager, "gestor", "Gestor123!", "Gestor", company.Id);
        await EnsureUserAsync(userManager, "monitoreo", "Monitoreo123!", "Monitoreo", company.Id);
        await EnsureUserAsync(userManager, "AMIDAS", "AMIDAS123!", "Vendedor", company.Id);
        await EnsureUserAsync(userManager, "SUPERADMIN", "ADMIN", "SuperAdmin", null);

        await EnsureStatusesAsync(db, company.Id);
        await EnsureCreatinaAsync(db, company.Id);

        await db.SaveChangesAsync();
    }

    private static async Task EnsureUserAsync(UserManager<ApplicationUser> userManager, string username, string password, string role, int? companyId)
    {
        var user = await userManager.FindByNameAsync(username);
        if (user is null)
        {
            user = new ApplicationUser
            {
                UserName = username,
                Email = $"{username}@local.test",
                EmailConfirmed = true,
                CompanyId = companyId
            };

            var result = await userManager.CreateAsync(user, password);
            if (!result.Succeeded)
            {
                var error = string.Join(", ", result.Errors.Select(x => x.Description));
                throw new InvalidOperationException($"No se pudo crear el usuario {username}: {error}");
            }
        }
        else if (user.CompanyId != companyId)
        {
            user.CompanyId = companyId;
            await userManager.UpdateAsync(user);
        }

        if (!await userManager.IsInRoleAsync(user, role))
        {
            var currentRoles = await userManager.GetRolesAsync(user);
            if (currentRoles.Count > 0)
            {
                await userManager.RemoveFromRolesAsync(user, currentRoles);
            }

            await userManager.AddToRoleAsync(user, role);
        }
    }

    private static async Task EnsureStatusesAsync(ApplicationDbContext db, int companyId)
    {
        var legacyClienteStatus = await db.Statuses.FirstOrDefaultAsync(x => x.CompanyId == companyId && x.Name == "Cliente");
        var clientesStatus = await db.Statuses.FirstOrDefaultAsync(x => x.CompanyId == companyId && x.Name == "Clientes");

        if (legacyClienteStatus is not null && clientesStatus is null)
        {
            legacyClienteStatus.Name = "Clientes";
            clientesStatus = legacyClienteStatus;
        }

        var defaultStatuses = new[]
        {
            new { Name = "Clientes", BadgeClass = "success", SortOrder = 1 },
            new { Name = "Rechazo", BadgeClass = "danger", SortOrder = 2 },
            new { Name = "Interesado", BadgeClass = "info", SortOrder = 3 },
            new { Name = "Por Pagar", BadgeClass = "warning", SortOrder = 4 },
            new { Name = "Prospecto", BadgeClass = "primary", SortOrder = 5 }
        };

        foreach (var item in defaultStatuses)
        {
            var status = await db.Statuses.FirstOrDefaultAsync(x => x.CompanyId == companyId && x.Name == item.Name);
            if (status is null)
            {
                db.Statuses.Add(new StatusCatalog
                {
                    CompanyId = companyId,
                    Name = item.Name,
                    BadgeClass = item.BadgeClass,
                    SortOrder = item.SortOrder,
                    IsActive = true
                });
            }
            else
            {
                status.BadgeClass = item.BadgeClass;
                status.SortOrder = item.SortOrder;
                status.IsActive = true;
            }
        }
    }

    private static async Task EnsureCreatinaAsync(ApplicationDbContext db, int companyId)
    {
        var creatina = await db.Products
            .Include(x => x.Prices)
            .FirstOrDefaultAsync(x => x.CompanyId == companyId && x.Name == "Creatina");

        if (creatina is null)
        {
            creatina = new Product
            {
                CompanyId = companyId,
                Name = "Creatina",
                IsActive = true,
                Prices = new List<ProductPrice>
                {
                    new() { Quantity = 1, Price = 89m },
                    new() { Quantity = 2, Price = 149m },
                    new() { Quantity = 3, Price = 189m }
                }
            };

            db.Products.Add(creatina);
        }
        else
        {
            creatina.IsActive = true;
            await EnsurePriceAsync(db, creatina.Id, 1, 89m);
            await EnsurePriceAsync(db, creatina.Id, 2, 149m);
            await EnsurePriceAsync(db, creatina.Id, 3, 189m);
        }
    }

    private static async Task EnsurePriceAsync(ApplicationDbContext db, int productId, int quantity, decimal price)
    {
        var productPrice = await db.ProductPrices.FirstOrDefaultAsync(x => x.ProductId == productId && x.Quantity == quantity);
        if (productPrice is null)
        {
            db.ProductPrices.Add(new ProductPrice
            {
                ProductId = productId,
                Quantity = quantity,
                Price = price
            });

            return;
        }

        productPrice.Price = price;
    }
}
