// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuplementosApp.Web.Data;

#nullable disable

namespace SuplementosApp.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307210147_AddTipoContacto")]
    partial class AddTipoContacto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuplementosApp.Web.Data.CanalVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CanalesVenta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Orgánico"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Shopify"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "WhatsApp"
                        });
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.CategoriaGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasGasto", (string)null);
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.EstadoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EstadosVenta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "COMPROBANTE PROVINCIA"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "En destino"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Entregado"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Enviado"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Lima embalado"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Por enviar provincia"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Cancelado/No quiere"
                        });
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.ToTable("Gastos", (string)null);
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.MetodoEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MetodosEnvio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Shalom"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Olva Courier"
                        });
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MetodosPago", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Yape"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "BCP"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Plin"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Mercado Pago"
                        });
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.ReporteDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AOV")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CPA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostoPorMensaje")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FacturacionTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GastoPublicidadFB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ROAS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TasaCierre")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TotalMensajes")
                        .HasColumnType("int");

                    b.Property<int>("TotalPedidos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("ReporteDiario", (string)null);
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.ReporteDiarioDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Facturado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mensajes")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pedidos")
                        .HasColumnType("int");

                    b.Property<decimal>("Publicidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReporteDiarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaCierre")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReporteDiarioId");

                    b.HasIndex("VendedorId");

                    b.ToTable("ReporteDiarioDetalle", (string)null);
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.SeguimientoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("LlamadaRealizada")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoInteres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SeguimientoClientes", (string)null);
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("ComisionBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendedores", (string)null);
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanalVentaId")
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Clave")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DNI")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EstadoVentaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoEnvioId")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NroOrden")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Productos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoContacto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Lead");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanalVentaId");

                    b.HasIndex("EstadoVentaId");

                    b.HasIndex("MetodoEnvioId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.Gasto", b =>
                {
                    b.HasOne("SuplementosApp.Web.Data.CategoriaGasto", "CategoriaGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaGastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaGasto");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.ReporteDiarioDetalle", b =>
                {
                    b.HasOne("SuplementosApp.Web.Data.ReporteDiario", "ReporteDiario")
                        .WithMany("Detalles")
                        .HasForeignKey("ReporteDiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuplementosApp.Web.Data.Vendedor", "Vendedor")
                        .WithMany("ReportesDiariosDetalle")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReporteDiario");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.Venta", b =>
                {
                    b.HasOne("SuplementosApp.Web.Data.CanalVenta", "CanalVenta")
                        .WithMany("Ventas")
                        .HasForeignKey("CanalVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuplementosApp.Web.Data.EstadoVenta", "EstadoVenta")
                        .WithMany("Ventas")
                        .HasForeignKey("EstadoVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuplementosApp.Web.Data.MetodoEnvio", "MetodoEnvio")
                        .WithMany("Ventas")
                        .HasForeignKey("MetodoEnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuplementosApp.Web.Data.MetodoPago", "MetodoPago")
                        .WithMany("Ventas")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuplementosApp.Web.Data.Vendedor", "Vendedor")
                        .WithMany("Ventas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanalVenta");

                    b.Navigation("EstadoVenta");

                    b.Navigation("MetodoEnvio");

                    b.Navigation("MetodoPago");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.CanalVenta", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.CategoriaGasto", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.EstadoVenta", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.MetodoEnvio", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.MetodoPago", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.ReporteDiario", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SuplementosApp.Web.Data.Vendedor", b =>
                {
                    b.Navigation("ReportesDiariosDetalle");

                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
